In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#Import library
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
dd = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Amikom Sehat/Data_diabetes (1).csv', 
                 usecols= ['Sex', 'Age',    'Diabetes_012', 'HighBP',   'HighChol',    'BMI',  'Smoker',   'Stroke',   
                 'HeartDiseaseorAttack',    'PhysActivity','Fruits', 'Veggies'])

In [ ]:
dd

,Diabetes_012,Sex,Age,HighBP,HighChol,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies
0,0,0,61,1,1,40,1,0,0,0,0,1
1,0,0,45,0,0,25,1,0,0,1,0,0
2,0,0,61,1,1,28,0,0,0,0,1,0
3,0,0,63,1,0,27,0,0,0,1,1,1
4,0,0,63,1,1,24,0,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0,1,23,1,1,45,0,0,0,0,1,1
253676,2,0,63,1,1,18,0,0,0,0,0,0
253677,0,0,19,0,0,28,0,0,0,1,1,0
253678,0,1,45,1,0,23,0,0,0,0,1,1
253679,2,0,61,1,1,25,0,0,1,1,1,0

In [ ]:
#membaca 5 data teratas dari dataset
dd.head(5)

,Diabetes_012,Sex,Age,HighBP,HighChol,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies
0,0,0,61,1,1,40,1,0,0,0,0,1
1,0,0,45,0,0,25,1,0,0,1,0,0
2,0,0,61,1,1,28,0,0,0,0,1,0
3,0,0,63,1,0,27,0,0,0,1,1,1
4,0,0,63,1,1,24,0,0,0,1,1,1

In [ ]:
#membaca 5 data terakhir dari dataset
dd.tail(5)

,Diabetes_012,Sex,Age,HighBP,HighChol,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies
253675,0,1,23,1,1,45,0,0,0,0,1,1
253676,2,0,63,1,1,18,0,0,0,0,0,0
253677,0,0,19,0,0,28,0,0,0,1,1,0
253678,0,1,45,1,0,23,0,0,0,0,1,1
253679,2,0,61,1,1,25,0,0,1,1,1,0

In [ ]:
#mengetahui berapa baris dan kolom
dd.shape

(253680, 12)

In [ ]:
#mengetahui info data
dd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Diabetes_012          253680 non-null  int64
 1   Sex                   253680 non-null  int64
 2   Age                   253680 non-null  int64
 3   HighBP                253680 non-null  int64
 4   HighChol              253680 non-null  int64
 5   BMI                   253680 non-null  int64
 6   Smoker                253680 non-null  int64
 7   Stroke                253680 non-null  int64
 8   HeartDiseaseorAttack  253680 non-null  int64
 9   PhysActivity          253680 non-null  int64
 10  Fruits                253680 non-null  int64
 11  Veggies               253680 non-null  int64
dtypes: int64(12)
memory usage: 23.2 MB

In [ ]:
#melihat apakah ada data yang kosong
dd.isnull().sum()

Diabetes_012            0
Sex                     0
Age                     0
HighBP                  0
HighChol                0
BMI                     0
Smoker                  0
Stroke                  0
HeartDiseaseorAttack    0
PhysActivity            0
Fruits                  0
Veggies                 0
dtype: int64

In [ ]:
#melihat statistik data
dd.describe()

,Diabetes_012,Sex,Age,HighBP,HighChol,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies
count,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000
mean,0.296921,0.440342,49.213052,0.429001,0.424121,28.382364,0.443169,0.040571,0.094186,0.756544,0.634256,0.811420
std,0.698160,0.496429,17.781600,0.494934,0.494210,6.608694,0.496761,0.197294,0.292087,0.429169,0.481639,0.391175
min,0.000000,0.000000,18.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,42.000000,0.000000,0.000000,24.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
50%,0.000000,0.000000,46.000000,0.000000,0.000000,27.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
75%,0.000000,1.000000,62.000000,1.000000,1.000000,31.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000
max,2.000000,1.000000,80.000000,1.000000,1.000000,98.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
# memeriksa distribusi data Variabel Target ( 1 : positif , 0 : negatif )
dd['Diabetes_012'].value_counts()

0    213703
2     35346
1      4631
Name: Diabetes_012, dtype: int64

In [ ]:
# memeriksa distribusi Variabel Target
dd['Sex'].value_counts()

0    141974
1    111706
Name: Sex, dtype: int64

In [ ]:
#X : data selain kolom target
X = dd.drop(columns='Diabetes_012', axis=1)

#Y : data kolom target
Y = dd['Diabetes_012']

In [ ]:
#melihat data x
X

,Sex,Age,HighBP,HighChol,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies
0,0,61,1,1,40,1,0,0,0,0,1
1,0,45,0,0,25,1,0,0,1,0,0
2,0,61,1,1,28,0,0,0,0,1,0
3,0,63,1,0,27,0,0,0,1,1,1
4,0,63,1,1,24,0,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
253675,1,23,1,1,45,0,0,0,0,1,1
253676,0,63,1,1,18,0,0,0,0,0,0
253677,0,19,0,0,28,0,0,0,1,1,0
253678,1,45,1,0,23,0,0,0,0,1,1
253679,0,61,1,1,25,0,0,1,1,1,0

In [ ]:
#melihat data Y
Y

0         0
1         0
2         0
3         0
4         0
         ..
253675    0
253676    2
253677    0
253678    0
253679    2
Name: Diabetes_012, Length: 253680, dtype: int64

In [ ]:
#memisahkan data mejadi data training dan data test
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(253680, 11) (126840, 11) (126840, 11)



---

**MODEL TRAINING**

In [ ]:
#Menggunakan model logika regressi
model = LogisticRegression()

In [ ]:
#Training model logika regressi dengan data training
model.fit(X_train, Y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

LogisticRegression()



---

**MODEL EVALUASI**

In [ ]:
# Acurracy pada data training

X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print('Accuracy pada data training : ', training_data_accuracy)

Accuracy pada data training :  0.8439766635130873

In [ ]:
import pickle
filename = 'model_Diabetes.pkl'
pickle.dump(model, open(filename, 'wb'))

---

**MEMBUAT SYSTEM PREDIKSI**

In [ ]:
#input : Jenis Kelamin, Umur, Tekanan darah, colestroll, BMI, Merokok,  Stroke, Serangan jantung, Aktivitas berat, Mengkonsumsi buah, Mengkonsumsi sayur.
input_data = (1,	30,	1,	1,	46,	1,	1, 0,	1,	1,	0)

#mennganti input data menjadi numpy array
input_data_array = np.array(input_data)

#
input_data_reshape = input_data_array.reshape(1,-1)

prediksi = model.predict(input_data_reshape)
print(prediksi)

if (prediksi[0]==0):
  print('Anda tidak terindikasi penyakit Diabetes')
elif (prediksi[0]==1):
  print('Anda terindikasi prediabetes')
else:
  print('Anda terindikasi penyakit Diabetes')

[2]
Anda mempunyai penyakit Diabetes

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  "X does not have valid feature names, but"