In [ ]:
BBMfrom google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#import dependency
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
#import dataset dari gdrive
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Amikom Sehat/bmi.csv')

In [ ]:
#baca dataset
data

     Gender  Height  Weight  Index
0         0     174      96      4
1         0     189      87      2
2         1     185     110      4
3         1     195     104      3
4         0     149      61      3
..      ...     ...     ...    ...
495       1     150     153      5
496       1     184     121      4
497       1     141     136      5
498       0     150      95      5
499       0     173     131      5

[500 rows x 4 columns]

In [ ]:
#baca 5 data teratas
data.head()

   Gender  Height  Weight  Index
0       0     174      96      4
1       0     189      87      2
2       1     185     110      4
3       1     195     104      3
4       0     149      61      3

In [ ]:
#baca 5 data terakhir
data.tail()

     Gender  Height  Weight  Index
495       1     150     153      5
496       1     184     121      4
497       1     141     136      5
498       0     150      95      5
499       0     173     131      5

In [ ]:
#mengetahui jumlah baris dan kolom
data.shape

(500, 4)

In [ ]:
#mengetahui info data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Gender  500 non-null    int64
 1   Height  500 non-null    int64
 2   Weight  500 non-null    int64
 3   Index   500 non-null    int64
dtypes: int64(4)
memory usage: 15.8 KB

In [ ]:
#cek apakah ada data kosong
data.isnull().sum()

Gender    0
Height    0
Weight    0
Index     0
dtype: int64

In [ ]:
#melihat statistik data
data.describe()

           Gender      Height      Weight       Index
count  500.000000  500.000000  500.000000  500.000000
mean     0.510000  169.944000  106.000000    3.748000
std      0.500401   16.375261   32.382607    1.355053
min      0.000000  140.000000   50.000000    0.000000
25%      0.000000  156.000000   80.000000    3.000000
50%      1.000000  170.500000  106.000000    4.000000
75%      1.000000  184.000000  136.000000    5.000000
max      1.000000  199.000000  160.000000    5.000000

In [ ]:
#cek distribusi data variabel target 0 = sangat kurus, 1 = kurus, 2 = normal, 3 = kegemukan, 4 = obesitas, 5 = obesitas ekstrim
data['Index'].value_counts()
data['Gender'].value_counts()

1    255
0    245
Name: Gender, dtype: int64

In [ ]:
#pembagian data
#X = data selain Index yang dicari
x = data.drop(columns='Index', axis=1)

#y = data Index / yang dicari
y = data['Index']

In [ ]:
#lihat data x
x

     Gender  Height  Weight
0         0     174      96
1         0     189      87
2         1     185     110
3         1     195     104
4         0     149      61
..      ...     ...     ...
495       1     150     153
496       1     184     121
497       1     141     136
498       0     150      95
499       0     173     131

[500 rows x 3 columns]

In [ ]:
#lihat data y
y

0      4
1      2
2      4
3      3
4      3
      ..
495    5
496    4
497    5
498    5
499    5
Name: Index, Length: 500, dtype: int64

In [ ]:
#membagi data training dan data test
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2,stratify=y, random_state=2)

In [ ]:
#cek hasil pembagian data training dan data test
print(x.shape, x_train.shape, x_test.shape, y.shape, y_train.shape, y_test.shape)

(500, 3) (400, 3) (100, 3) (500,) (400,) (100,)

In [ ]:
#Model Data
#Logika Regresi
model=LogisticRegression()

In [ ]:
#Training model logika regressi dengan data training
model.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

LogisticRegression()

In [ ]:
#Evaluasi
# Acurracy pada data training

x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)

print('Accuracy pada data training : ', training_data_accuracy)

Accuracy pada data training :  0.7225

In [ ]:
import pickle
filename = 'model_BMI.pkl'
pickle.dump(model, open(filename, 'wb'))

In [ ]:
#input(Gender, Tinggi, Berat)
input_data = (0,180,80)

#mennganti input data menjadi numpy array
input_data_array = np.array(input_data)

#
input_data_reshape = input_data_array.reshape(1,-1)

prediksi = model.predict(input_data_reshape)
print(prediksi)

if (prediksi[0]==0):
  print('Anda Sangat Kurus')
elif (prediksi[0]==1):
  print('Anda Kurus')
elif (prediksi[0]==2):
  print('Anda Normal')
elif (prediksi[0]==3):
  print('Anda Kegemukan')
elif (prediksi[0]==4):
  print('Anda Obesitas')
else:
  print('Anda Obesitas Ekstrim')

[2]
Anda Normal

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  "X does not have valid feature names, but"